name: Sync to Upstream
on:
  schedule:
    - cron: '0 10 * * *' # 每天北京时间18点自动检查更新
  workflow_dispatch:      # 允许你手动点击运行
jobs:
  update_external_repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sync with upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_repository: suenway/danmu-api # 这里填原作者的仓库名，通常是这个
          upstream_branch: main
          target_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
